# ===========================================================================
# Module: Amazon Athena
# ===========================================================================
# Creates an Athena workgroup that downstream analysts and the Step Functions
# validation query use to query the lakehouse Delta tables.
#
# The workgroup enforces:
#   - A query result output location (so results don't scatter across S3)
#   - A bytes-scanned limit per query (cost control — prevents runaway scans)
#   - Engine version pinning (Athena v3 for Delta Lake support)
#   - Encryption on query results at rest

locals {
  prefix = "${var.project}-${var.environment}"
}

resource "aws_athena_workgroup" "main" {
  name = "${local.prefix}-workgroup"

  configuration {
    # Enforce the result location — individual queries can't override this
    enforce_workgroup_configuration = true

    # Cost control: limit each query to scanning 10 GB max.
    # Prevents an analyst from accidentally scanning the entire historical table.
    bytes_scanned_cutoff_per_query = 10737418240 # 10 GB

    result_configuration {
      output_location = "s3://${var.athena_results_bucket}/query-results/"

      encryption_configuration {
        encryption_option = "SSE_S3"
      }
    }

    engine_version {
      # Athena engine v3 supports Delta Lake tables natively via the
      # SymlinkTextInputFormat generated by the Glue Crawler.
      selected_engine_version = "Athena engine version 3"
    }
  }

  # Allow destruction in non-prod environments for easy cleanup.
  # In prod, set this to false and use force_destroy = false.
  force_destroy = var.environment != "prod"
}
